# Generated by Django 5.2.17 on 2026-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='community',
            field=models.CharField(blank=True, default='Berekum Central', max_length=100, null=True),
        ),
    ]
