# Generated by Django 6.1.1 on 2026-10-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_post_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
