# Generated by Django 6.1.1 on 2026-10-03 10:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="media",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="media"
            ),
        ),
    ]
